### PR TITLE
Documentation shift and minor changes

### PR DESCRIPTION
**Pull request by ashwani-rathee**
- This PR will add more tags for encoding.

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
Encoding also works on windows so we can close windows use too with this!

**Comment by ashwani-rathee** [comment]
@johnnychen94 can you please update the new docs link to https://juliaimages.org/ExifViewer.jl/dev/ ?

**Comment by johnnychen94** [comment]
@ashwani-rathee just gave you the admin permission.

**Comment by ashwani-rathee** [comment]
Got it!! tenks. How do I release a new version?

**Comment by johnnychen94** [comment]
There's already a v0.1.0 release https://github.com/JuliaRegistries/General/blob/master/E/ExifViewer/Versions.toml so you'll have to bump the version first in Project.toml and then do the regular registration as you did in https://github.com/JuliaImages/ExifViewer.jl/issues/9

**Pull request merged**
